### ISSUE TITLE
Add releases to Github

### ISSUE THREAD

**Issue by chelming** [RITJBF/JBioFramework#9]
It would be nice if releases were tagged on github instead of having to go download from sourceforge.

**Comment by atla5** [comment]
Thanks for the contribution! 

### rationale

It likely is a hassle to go to a separate site (or perhaps two if you went to our website too), but one of the reasons we haven't put a download here is because SourceForge does a very good job tracking them.

### question

Currently the repositories on both sites are linked [1], but I'm unsure:
- if SourceForge counts downloads from GitHub, or
- how to manage and count GitHub downloads separately

### resources

[1] SourceForge Screenshot with 'GitHub' tab. 
![sourceforge screenshot showing 'github' tab](https://cloud.githubusercontent.com/assets/5565284/17523774/c1f1ce86-5e29-11e6-95fa-2ab7a694422a.png)
[2] git-scm [basic tagging guide](https://git-scm.com/book/en/v2/Git-Basics-Tagging)

**Comment by atla5** [comment]
I could embed the download link in the README.md description. 

Would that help?

**Comment by chelming** [comment]
I'm just biased to GitHub :). I'm automating downloading/packaging/deploying the latest version of JBF, it really doesn't matter too much whether it's on SourceForge or tagged as a release on GitHub.

**Comment by joshuapouliot27** [comment]
I had recently finished, in the Development branch, the automated build script and automated uploading of the zip file from travis-ci.org to GitHub when a commit is tagged.  Sourceforge is also configured to automatically mirror releases from GitHub  whenever a release is posted.  We are able to track how many times a specific file is downloaded from GitHub using the GitHub API ([JBioFramework Releases](https://api.github.com/repos/RITJBF/JBioFramework/releases)).
